README.md
main.tf
test/fixtures/minimal/README.md
variables.tf

Enables the "redis.googleapis.com" service on the targeted project if the `enable_apis` variable is `true`. Defaults to `true` with what we consider to be the most basic module use case in mind - a brand new project is targeted and service enablement is not already managed by other means.
Integration tests now pass successfully when targeting a new, pristine project. As previously or with `enable_apis` set to `false`, tests will fail run against a pristine project with `Error 403: Google Cloud Memorystore for Redis API has not been used in project <PROJECT_ID> before or it is disabled...`.

Optionally Enable "redis.googleapis.com" Service

---

.kitchen.yml
Makefile
build/int.cloudbuild.yaml
build/lint.cloudbuild.yaml
examples/memcache/main.tf
examples/memcache/memcache.tf
examples/memcache/outputs.tf
examples/memcache/variables.tf
examples/memcache/versions.tf
modules/memcache/README.md
modules/memcache/main.tf
modules/memcache/outputs.tf
modules/memcache/variables.tf
test/fixtures/memcache/README.md
test/fixtures/memcache/main.tf
test/fixtures/memcache/outputs.tf
test/fixtures/memcache/terraform.tfvars.example
test/fixtures/memcache/variables.tf
test/fixtures/memcache/versions.tf
test/integration/memcache/controls/gcloud.rb
test/integration/memcache/inspec.yml
test/setup/main.tf
test/setup/versions.tf

This PR is mostly working with 2 exceptions:
1. When ever I apply or destroy the resource, the response from the API is always a 403 claiming the API isn't enabled. 
```Error: Error waiting for Deleting Instance: error while retrieving operation: googleapi: Error 403: Cloud Memorystore for Memcached API has not been used in project ######## before or it is disabled```
However, I assure you the API is enabled, and the GSA creating the resource has permissions.. because the instance actually gets created! (or destroyed if I need be). it's just the API seems to respond with a 403 no matter what.
2.  When I attempt to set `memcache_parameters` attribute, it plans fine, but then fails to apply w/ a different error from the API:
```
Error: Error waiting for Deleting Instance: error while …
```

feat: submodule for cloud memorystore (memcache)

---

main.tf

Hi!
Interpolation-only expressions are deprecated since terraform 0.11
Terraform warning: 
```
Warning: Interpolation-only expressions are deprecated
on .terraform/modules/memorystore/main.tf line 44, in module "enable_apis":
44:   project_id  = "${var.project}"
Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.
Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that …
```

Remove interpolation-only expressions

---

main.tf
modules/memcache/main.tf

Upgrade version constraint of `project_services` module to `v9.2.0`.
It allows to use Terraform 0.13.
```hcl
terraform {
required_version = ">=0.12.6, <0.14"
}
```

Upgrade version of project_services module to 9.2.0

---

README.md

The version in the README.md's example used version 2.0.0 of the module, which is old. The 4.0.0 is the current latest version.
Fixes #69

Updated version in the README example hcl

---

examples/memcache/outputs.tf
modules/memcache/README.md
modules/memcache/outputs.tf
test/integration/memcache/inspec.yml

google_memcache_instance exports a discovery_endpoint that would be useful to upstream modules for things like assigning a DNS name to that endpoint instead of each node address.

Add discovery endpoint output to memcache module

---

README.md
outputs.tf
test/fixtures/redis/README.md
test/fixtures/redis/outputs.tf
test/integration/redis/controls/gcloud.rb
test/integration/redis/inspec.yml

feat: Add missing auth_string output. Fix #76

---

README.md
main.tf
variables.tf

I added the options to choose the read replicas types and number according to gcp documentation and terrraform
https://cloud.google.com/memorystore/docs/redis/reference/rest/v1/projects.locations.instances#readreplicasmode
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/redis_instance

added replica_count and replicas_mode functionality

---

outputs.tf

Fix: add sensitive flag on the `auth_string` output so it stops breaking applies on tf 1+
Solves issue https://github.com/terraform-google-modules/terraform-google-memorystore/issues/86

fix: add sensitive true flag to output auth_string

---

README.md
main.tf
outputs.tf
variables.tf

Changes added to support setup with read replicas.
Input `secondary_ip_range` is required while enabling read replica on existing memorystore instance.
Output `read_endpoint` is useful when read replicas are enabled.

Feat: add support for using read replicas

---

examples/memcache/main.tf
modules/memcache/README.md
modules/memcache/variables.tf

The duration attribute of the maintenance policy for Memcached is expected a string, not a number. [Doc Link](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/memcache_instance#duration)
Upon passing the number in Memcached maintence_policy, terraform is throwing an Illegal duration format error because it's expecting the value to end with 's', for example, '10800s'. Refer to the attached screenshot.
Screenshot 2023-03-16 at 4 35 06 PM
Since the value type is set as a number right now which means it will not expect string and throws The given value is not suitable for module.memcached_memorystore.var.maintenance_policy.
Added maintenance_policy block in the example.
Note: The code is tested and working. It's able to create a Memcached memstore with a …

Fix: Change memcached's maintenance_policy duration attribute type.

---

Makefile
README.md
examples/redis-cluster/main.tf
examples/redis/README.md
examples/redis/outputs.tf
metadata.yaml
modules/memcache/metadata.yaml
modules/redis-cluster/metadata.yaml
outputs.tf
test/integration/redis-cluster/redis_cluster_test.go
test/integration/redis/redis_test.go

This PR makes below changes,
1. Add new output called env_vars for Redis
2. Update metadata files using `make generate_docs`

feat: Add new output called env_vars for Redis

---

Makefile
README.md
examples/redis/main.tf
metadata.yaml
modules/memcache/README.md
modules/memcache/metadata.yaml
modules/redis-cluster/metadata.yaml

This PR makes below changes,
1. Adds connection metadata manually to metadata.yaml
2. Adds output type manually to metadata.yaml

chore: add connection metadata and output type

---

outputs.tf

The latest addition to the output, `apphub_service_uri`, breaks the module due to the use of `var.region` which isn't a required variable and defaults to `null`.
Getting the region from the `google_redis_instance` resource instead will fix this.
```
│ Error: Invalid template interpolation value
│
│   on .terraform/modules/redis/outputs.tf line 75, in output "apphub_service_uri":
│   75:     service_id  = substr("${var.name}-${md5("${var.region}-${var.project_id}")}", 0, 63)
│     ├────────────────
│     │ var.region is null
│
│ The expression result is null. Cannot include a null value in a string template.
```
fixes #247

fix: Broken module due to apphub_service_uri output

---

README.md
docs/upgrading_to_v13.0.md
metadata.display.yaml
metadata.yaml
outputs.tf

We are removing apphub_service_uri as memorystore is not yet supported by AppHub

fix!: remove apphub_service_uri output and update metadata display yaml

---

README.md
main.tf
variables.tf

This pull requests solves my issues #271 and allows the setting of a custom description for the maintenance policy.

feat: allows setting a description for the maintenance policy

---

modules/redis-cluster/README.md

README had `project` instead of `project_id` under usage. If user used as a reference, two errors would happen.
- The argument "project_id" is required, but no definition was found.
- An argument named "project" is not expected here.

chore: Update README.md

---

modules/redis-cluster/metadata.display.yaml

This PR sets the visibility to "VISIBILITY_ROOT" for required output variables in redis-cluster's metadata.display.yaml
Purpose: This is an essential step in making Redis-cluster's Terraform blueprint ADC compliant.

chore: set visibility of output variables for redis-cluster 

---

modules/redis-cluster/metadata.yaml

Purpose: This is an essential step in making Redis-cluster's Terraform blueprint ADC compliant. 
This PR adds the type field to all output variables in the Redis Cluster's metadata.yaml.

chore: add output types to Redis Cluster's metadata.yaml for ADC compliance

---

Makefile
metadata.yaml
modules/memcache/metadata.yaml
modules/redis-cluster/metadata.yaml
modules/valkey/metadata.yaml
test/setup/iam.tf
test/setup/main.tf

Introduced:
- per_module_roles: to config required roles to run each sub modules.
- per_module_service: to config required services to run each sub modules.
Added feature flag --per-module-requirements to generate_docs cmd, to align with the per module configs.

feat: per module requirements configs
